# Generated by Django 4.1.2 on 2022-10-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('marca', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
    ]
